version: '3.8'
services:
  nginx:
    container_name: nginx-rudn-landing
    restart: unless-stopped
    build:
      context:
        .
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    driver: bridge